CREATE TABLE Venta (
  IdVenta NOT NULL PRIMARY KEY IDENTITY(1,1),
  Nombre VARCHAR(50) NOT NULL,
  Total MONEY
);

CREATE TABLE Concepto (
  Id NOT NULL PRIMARY KEY IDENTITY(1,1),
  Producto VARCHAR(50) NOT NULL,
  Cantidad VARCHAR(50) NOT NULL
);
